package cmd

import (
	"encoding/json"
	"strings"
	"testing"
)

func TestBundleList(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name    string
		args    []string
		wantErr bool
		check   func(t *testing.T, stdout string)
	}{
		{
			name: "default lists names only",
			args: []string{"bundle", "list"},
			check: func(t *testing.T, stdout string) {
				if stdout != "py-app\npy-code\n" {
					t.Errorf("stdout = %q, want sorted names one per line", stdout)
				}
			},
		},
		{
			name: "long adds descriptions",
			args: []string{"bundle", "list", "--long"},
			check: func(t *testing.T, stdout string) {
				if !strings.Contains(stdout, "Python code rules") {
					t.Errorf("stdout = %q, want a description column", stdout)
				}
			},
		},
		{
			name: "l is shorthand for long",
			args: []string{"bundle", "list", "-l"},
			check: func(t *testing.T, stdout string) {
				if !strings.Contains(stdout, "Python code rules") {
					t.Errorf("stdout = %q, want a description column", stdout)
				}
			},
		},
		{
			name: "json emits a parseable array",
			args: []string{"bundle", "list", "--json"},
			check: func(t *testing.T, stdout string) {
				var entries []struct{ Name, Description string }
				if err := json.Unmarshal([]byte(stdout), &entries); err != nil {
					t.Fatalf("stdout is not JSON: %v", err)
				}
				if len(entries) != 2 || entries[1].Name != "py-code" {
					t.Errorf("entries = %+v, want both bundles", entries)
				}
			},
		},
		{
			name:    "an argument is an error with empty stdout",
			args:    []string{"bundle", "list", "extra"},
			wantErr: true,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			stdout, _, err := run(t, testFS(), tc.args...)
			if tc.wantErr {
				if err == nil {
					t.Error("want error, got nil")
				}
				if stdout != "" {
					t.Errorf("stdout = %q, want empty on failure", stdout)
				}
				return
			}
			if err != nil {
				t.Fatalf("run(%v): %v", tc.args, err)
			}
			tc.check(t, stdout)
		})
	}
}

func TestBundleShow(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name    string
		args    []string
		wantErr bool
		want    []string
	}{
		{
			name: "assembles every fragment under a header",
			args: []string{"bundle", "show", "py-code"},
			want: []string{"Generated by moon", "# Core", "# Style"},
		},
		{
			name: "include expands to the same content",
			args: []string{"bundle", "show", "py-app"},
			want: []string{"# Core", "# Style"},
		},
		{
			name:    "unknown bundle is an error with empty stdout",
			args:    []string{"bundle", "show", "nope"},
			wantErr: true,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			stdout, _, err := run(t, testFS(), tc.args...)
			if tc.wantErr {
				if err == nil {
					t.Error("want error, got nil")
				}
				if stdout != "" {
					t.Errorf("stdout = %q, want empty on failure", stdout)
				}
				return
			}
			if err != nil {
				t.Fatalf("run(%v): %v", tc.args, err)
			}
			for _, w := range tc.want {
				if !strings.Contains(stdout, w) {
					t.Errorf("stdout missing %q", w)
				}
			}
		})
	}
}

func TestBundleExpand(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name    string
		args    []string
		wantErr bool
	}{
		{name: "flat bundle", args: []string{"bundle", "expand", "py-code"}},
		{name: "include resolved", args: []string{"bundle", "expand", "py-app"}},
		{name: "unknown bundle", args: []string{"bundle", "expand", "nope"}, wantErr: true},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			stdout, stderr, err := run(t, testFS(), tc.args...)
			if tc.wantErr {
				if err == nil {
					t.Error("want error, got nil")
				}
				if stdout != "" {
					t.Errorf("stdout = %q, want empty on failure", stdout)
				}
				return
			}
			if err != nil {
				t.Fatalf("run(%v): %v", tc.args, err)
			}
			if stdout != "_core\npython/style\n" {
				t.Errorf("stdout = %q, want the ordered fragment paths", stdout)
			}
			if !strings.Contains(stderr, "[*] 2 fragments") {
				t.Errorf("stderr = %q, want the fragment count", stderr)
			}
		})
	}
}
