package bundler

import (
	"errors"
	"strings"
	"testing"
	"testing/fstest"
)

func testFS() fstest.MapFS {
	return fstest.MapFS{
		"src/_core.md":        {Data: []byte("# Core\n")},
		"src/python/style.md": {Data: []byte("# Style\n")},
		"src/python/types.md": {Data: []byte("# Types\n")},
		"bundles/py-code":     {Data: []byte("# a comment\n_core.md\npython/style.md\n")},
		"bundles/py-app":      {Data: []byte("@include py-code\npython/types.md\n")},
		"bundles/cyc-a":       {Data: []byte("@include cyc-b\n")},
		"bundles/cyc-b":       {Data: []byte("@include cyc-a\n")},
		"bundles/broken":      {Data: []byte("python/ghost.md\n")},
	}
}

func TestRecipe(t *testing.T) {
	t.Parallel()
	e := New(testFS())

	tests := []struct {
		name   string
		bundle string
		want   []string
	}{
		{name: "flat list with comment stripped", bundle: "py-code", want: []string{"_core.md", "python/style.md"}},
		{name: "include expands in place", bundle: "py-app", want: []string{"_core.md", "python/style.md", "python/types.md"}},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got, err := e.Recipe(tc.bundle)
			if err != nil {
				t.Fatalf("Recipe(%q): %v", tc.bundle, err)
			}
			if strings.Join(got, ",") != strings.Join(tc.want, ",") {
				t.Errorf("Recipe(%q) = %v, want %v", tc.bundle, got, tc.want)
			}
		})
	}
}

func TestResolveErrors(t *testing.T) {
	t.Parallel()
	e := New(testFS())

	tests := []struct {
		name    string
		bundle  string
		wantErr error
	}{
		{name: "unknown bundle", bundle: "nope", wantErr: ErrUnknownBundle},
		{name: "include cycle", bundle: "cyc-a", wantErr: ErrIncludeCycle},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			_, err := e.Recipe(tc.bundle)
			if !errors.Is(err, tc.wantErr) {
				t.Fatalf("Recipe(%q) error = %v, want errors.Is(_, %v)", tc.bundle, err, tc.wantErr)
			}
		})
	}
}

func TestAssembleMissingFragment(t *testing.T) {
	t.Parallel()
	e := New(testFS())
	if _, err := e.Assemble("broken"); !errors.Is(err, ErrMissingFragment) {
		t.Fatalf("Assemble(broken) error = %v, want errors.Is(_, ErrMissingFragment)", err)
	}
}

func TestAssembleHeaderAndOrder(t *testing.T) {
	t.Parallel()
	e := New(testFS())
	out, err := e.Assemble("py-app")
	if err != nil {
		t.Fatalf("Assemble(py-app): %v", err)
	}
	s := string(out)
	if !strings.HasPrefix(s, "<!-- Generated by moon from bundles/py-app.") {
		t.Errorf("missing generated header, got:\n%s", s)
	}
	if i, j := strings.Index(s, "# Core"), strings.Index(s, "# Types"); i < 0 || j < 0 || i > j {
		t.Errorf("fragments out of order: core=%d types=%d", i, j)
	}
}

func TestCheck(t *testing.T) {
	t.Parallel()
	e := New(testFS())
	problems, orphans, err := e.Check()
	if err != nil {
		t.Fatalf("Check: %v", err)
	}
	if len(problems) == 0 {
		t.Error("expected problems (cycle + missing fragment), got none")
	}
	if len(orphans) != 0 {
		t.Errorf("expected no orphans, got %v", orphans)
	}
}

func TestHasBundleAndHasFragment(t *testing.T) {
	t.Parallel()
	e := New(testFS())

	if !e.HasBundle("py-code") {
		t.Error("HasBundle(py-code) = false, want true")
	}
	if e.HasBundle("nope") {
		t.Error("HasBundle(nope) = true, want false")
	}
	if e.HasBundle("bundles") { // a directory, not a file
		t.Error("HasBundle should not match a directory")
	}

	if !e.HasFragment("python/style.md") {
		t.Error("HasFragment(python/style.md) = false, want true")
	}
	if e.HasFragment("python/nope.md") {
		t.Error("HasFragment(python/nope.md) = true, want false")
	}
	if e.HasFragment("python") { // a directory, not a file
		t.Error("HasFragment should not match a directory")
	}
}

func TestDescription(t *testing.T) {
	t.Parallel()
	e := New(testFS())

	got, err := e.Description("py-code")
	if err != nil {
		t.Fatalf("Description: %v", err)
	}
	want := "a comment"
	if got != want {
		t.Errorf("Description(py-code) = %q, want %q", got, want)
	}

	if _, err := e.Description("nope"); !errors.Is(err, ErrUnknownBundle) {
		t.Errorf("Description(nope) error = %v, want errors.Is(_, ErrUnknownBundle)", err)
	}

	// py-app has no leading comment (its recipe starts with @include); an empty
	// description is valid, not an error.
	got, err = e.Description("py-app")
	if err != nil {
		t.Fatalf("Description(py-app): %v", err)
	}
	if got != "" {
		t.Errorf("Description(py-app) = %q, want empty", got)
	}
}

func TestFragment(t *testing.T) {
	t.Parallel()
	e := New(testFS())

	data, err := e.Fragment("python/style.md")
	if err != nil {
		t.Fatalf("Fragment: %v", err)
	}
	s := string(data)
	if !strings.HasPrefix(s, "<!-- Fragment: src/python/style.md -->") {
		t.Errorf("missing fragment header, got:\n%s", s)
	}
	if !strings.Contains(s, "# Style") {
		t.Errorf("missing fragment content, got:\n%s", s)
	}

	if _, err := e.Fragment("python/ghost.md"); !errors.Is(err, ErrMissingFragment) {
		t.Errorf("Fragment(ghost) error = %v, want errors.Is(_, ErrMissingFragment)", err)
	}
}

func TestAssembleManyDedup(t *testing.T) {
	t.Parallel()
	e := New(testFS())
	// py-code -> _core.md, python/style.md ; py-app -> (via include) same base + python/types.md
	out, err := e.AssembleMany([]string{"py-code", "py-app"})
	if err != nil {
		t.Fatalf("AssembleMany: %v", err)
	}
	s := string(out)
	if n := strings.Count(s, "# Core"); n != 1 {
		t.Errorf("_core.md emitted %d times, want 1 (dedup across bundles failed)", n)
	}
	if n := strings.Count(s, "# Types"); n != 1 {
		t.Errorf("python/types.md emitted %d times, want 1", n)
	}
	if !strings.Contains(s, "bundles/py-code, py-app") {
		t.Errorf("multi-bundle header missing both names:\n%s", s)
	}
}

func TestAssembleEmitsBoundaryComments(t *testing.T) {
	t.Parallel()
	e := New(testFS())
	out, err := e.Assemble("py-app")
	if err != nil {
		t.Fatalf("Assemble: %v", err)
	}
	s := string(out)
	for _, want := range []string{"<!-- src/_core.md -->", "<!-- src/python/style.md -->", "<!-- src/python/types.md -->"} {
		if !strings.Contains(s, want) {
			t.Errorf("missing provenance comment %q", want)
		}
	}
	if strings.Contains(s, "\n\n\n") {
		t.Errorf("assembled output has a blank-line run longer than one:\n%s", s)
	}
}

func TestResolveRejectsUnknownDirective(t *testing.T) {
	t.Parallel()
	fsys := fstest.MapFS{
		"src/_core.md": {Data: []byte("# Core\n")},
		"bundles/typo": {Data: []byte("@includes _core.md\n")},
	}
	e := New(fsys)
	if _, err := e.Recipe("typo"); err == nil || !strings.Contains(err.Error(), "unknown directive") {
		t.Fatalf("Recipe(typo) error = %v, want an 'unknown directive' error", err)
	}
}

func TestAssembleDedupDiamond(t *testing.T) {
	t.Parallel()
	fsys := fstest.MapFS{
		"src/_core.md":    {Data: []byte("# Core\n")},
		"src/a.md":        {Data: []byte("# A\n")},
		"src/b.md":        {Data: []byte("# B\n")},
		"bundles/base":    {Data: []byte("_core.md\n")},
		"bundles/left":    {Data: []byte("@include base\na.md\n")},
		"bundles/right":   {Data: []byte("@include base\nb.md\n")},
		"bundles/diamond": {Data: []byte("@include left\n@include right\n")},
	}
	e := New(fsys)
	out, err := e.Assemble("diamond")
	if err != nil {
		t.Fatalf("Assemble(diamond): %v", err)
	}
	if n := strings.Count(string(out), "# Core"); n != 1 {
		t.Errorf("diamond include emitted _core.md %d times, want 1", n)
	}
}
